apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-server
  namespace: elastic-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-server
  template:
    metadata:
      labels:
        app: fleet-server
  spec:
    containers:
      - name: fleet-server
        image: docker.elastic.co/beats/elastic-agent:8.5.1
        env:
        - name: FLEET_SERVER_ENABLE
          value: "1"
        - name: FLEET_SERVER_ELASTICSEARCH_HOST
          value: "http://elasticsearch.elastic-system.svc:9200"
        - name: FLEET_SERVER_KIBANA_HOST
          value: "http://kibana.elastic-system.svc:5601"
        ports:
        - containerPort: 8220
---
apiVersion: v1
kind: Service
metadata:
  name: fleet-server
  namespace: elastic-system
spec:
  selector:
    app: fleet-server
  ports:
  - port: 8220
    targetPort: 8220
  type: LoadBalancer
